# 应用设置
[app]
    run_debug       = "true"
    app_name        = "gf-framework"
    app_host        = "127.0.0.1/"
    page_size       = "10"
    max_page_size   = "50"
    jwt_secret      = "23347$040412"

# 服务
[server]
    http_port       = 80
    read_timeout    = 60
    write_timeout   = 60

# 应用系统设置
[setting]
    runtime_path    = "runtime"
    temp_path       = "runtime/temp"
    log_path        = "runtime/logs"
    public_path     = "public"
    upload_path     = "public/upload/"
    image_path      = "public/images/"
    static_path     = "public/static/"
    view_path       = "template"

# 数据库连接
[database]
    prefix          = "qu_"
    link            = "mysql:root:123456@tcp(127.0.0.1:3306)/ak_test"

# Redis数据库配置
[redis]
    disk            = "host:port[,db,pass?maxIdle=x&maxActive=x&idleTimeout=x&maxConnLifetime=x]"